# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
assistant_id: 20241008-122638-flat-bag

# Configuration for Rasa NLU.
language: en

version: "3.0"  # Ensure that you are using the correct version (compatible with Rasa 3.x)
pipeline: 
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
policies: 
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100

# You can customize your Fallback behavior using RulePolicy for specific rules
rules:
  - rule: Fallback rule
    steps:
      - intent: _fallback
      - action: action_default_fallback

# Fallback action to handle undefined intents
actions:
  - action_default_fallback
